name: ${project.name}
version: ${project.version}
description: ${project.description}
author: ${project.authors}
main: ${project.main}
depend: [ProtocolLib]
commands:
  auracheck:
    description: Check if player has killaura hack
    usage: /<command> <username> - checks for killaura hack
    aliases: [ac]
    permission: auracheck.check
